sudo: false
dist: xenial

language: erlang

otp_release:
 - 20.3.8.5
 - 21.1.4
 - 21.2.5

install: "true"

before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod u+x ./rebar3

script:
  - ./rebar3 compile
  - ./rebar3 xref
  - ./rebar3 eunit
